# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

env:
  AZURE_STG_ACT_KEY: 1x8rUEt/OKNJieYPn4yHy7rpkB4bP7aqElMK7etiPU3698F/v8LF334C4hIZ/24bTrDcPW0VuYqF8rxygh04NA==

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2

      - name: Test Repo Secret
        env:
          REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}
          ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
          ORG_SECRET: ${{ secrets.MY_ORG_SECRET }}
        run: |
          Write-Host ("Repo Secret Value: " + $env:REPO_SECRET);
          Write-Host ("Test Repo Secret Value: " + ($env:REPO_SECRET -eq "reposecretvalue"));
          Write-Host ("Env Secret Value: " + $env:ENV_SECRET);
          Write-Host ("Test Env Secret Value: " + ($env:ENV_SECRET -eq "envsecretvaluedev"));
          Write-Host ("Org Secret Value: " + $env:ORG_SECRET);
          Write-Host ("Test Org Secret Value: " + ($env:ORG_SECRET -eq "myorgsecretvalue"));
